# Generated by Django 4.2.6 on 2023-10-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserDashbord', '0003_alter_gdform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='images/imag-1.jpg', upload_to='profile_images/'),
        ),
    ]
